### ISSUE TITLE
Get VDJTools working on ExaCloud

### ISSUE THREAD

**Issue by leyshock** [ohsu-computational-biology/tcr_sequencing_tools#12]
VDJTools currently throws errors when we try to run it on ExaCloud.  While we have a workaround (running VDJTools on our local machine), it requires us to scp the files from ExaCloud to our own machine.

Get VDJTools working on ExaCloud, and test it on several files.

**Comment by weshorton** [comment]
Requires java version 1.8, which is not the default download on exacloud. In any submission script, enter the following:
`export JAVA_HOME=/etc/alternatives/jre_1.8.0`
`export PATH=${JAVA_HOME}/bin:${PATH}`

Currently have the .jar file in the vdjtools directory. Right now, in all run files, should assign vdjtools variable like so:
`VDJTOOLS='java -Xmx10G -jar ./vdjtools-1.0.7.jar'`
